series: GLFW Graphics
title: Basic Particle Emitter
author:
  name: IGME-RIT
  email:
  github: igme-rit
description: This examples uses the code established in the OBJ Loading example to demonstrate a basic particle effect.
language: C++
tags:
  - Graphics
extra_resources:
connections:
  - series: GLFW Graphics
    title: Obj Loading
  - series: GLFW Graphics
    title: Multiple Lighting Tutorial
