title: Basic Particle Emitter
author:
  name: IGME-RIT
  email:
  github: igme-rit
description: This examples uses the code established in the OBJ Loading example to demonstrate a basic particle effect.
language: C++
image:
  icon: https://cloud.githubusercontent.com/assets/10502938/13506660/28be0300-e14d-11e5-90e3-b194f14e52bd.PNG
  banner: https://cloud.githubusercontent.com/assets/10502938/13506660/28be0300-e14d-11e5-90e3-b194f14e52bd.PNG
tags:
  - C++
  - Graphics
extra_resources:
  - 
connections:
  - "multiple-lighting-tutorial"
